export const SEED_TEMPLATES = [
  {
    version: '1.0.0',
    id: 'aws-vod-pipeline',
    kind: 'architecture',
    title: 'AWS Serverless Video-on-Demand Ingestion',
    description: 'A production-grade ingestion and media processing pipeline on AWS using Route 53, CloudFront, S3 upload, API Gateway, Lambda, MediaConvert and DynamoDB.',
    metadata: {
      complexity: 'Production',
      provider: 'aws',
      technologies: ['Route53', 'CloudFront', 'S3', 'Lambda', 'MediaConvert', 'DynamoDB'],
      tags: ['video-on-demand', 'media-processing', 'cloudfront', 'mediaconvert', 'analytics'],
      detailLevels: ['Executive', 'Engineering', 'Production']
    },
    nodes: [
      // Group: Users and Client Applications
      { id: 'content_admin', semanticType: 'external', label: 'Content Admin / Studio', technology: 'Operator Interface', icon: 'lucide:clapperboard', position: { x: -1632, y: 46 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'viewers', semanticType: 'external', label: 'Web, Mobile and Smart TV Viewers', technology: 'Audience Clients', icon: 'lucide:monitor-smartphone', position: { x: -1632, y: -146 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'video_player', semanticType: 'external', label: 'Adaptive Bitrate Video Player', technology: 'HLS Player Framework', icon: 'lucide:circle-play', position: { x: -1632, y: -338 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },

      // Group: AWS Edge and Access Layer
      { id: 'route53', semanticType: 'service', label: 'Amazon Route 53', technology: 'DNS Routing', icon: 'logos:aws-route53', position: { x: -617, y: -127 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'waf_shield', semanticType: 'service', label: 'AWS WAF + Shield', technology: 'DDoS Protection', icon: 'logos:aws-waf', position: { x: -169, y: -144 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'cloudfront', semanticType: 'service', label: 'Amazon CloudFront CDN', technology: 'Global Edge Cache', icon: 'logos:aws-cloudfront', position: { x: 247, y: -201 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'cognito', semanticType: 'service', label: 'Amazon Cognito', technology: 'User Identity Pool', icon: 'logos:aws-cognito', position: { x: -617, y: 65 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'api_gateway', semanticType: 'service', label: 'Amazon API Gateway', technology: 'REST Edge Controller', icon: 'logos:aws-api-gateway', position: { x: -169, y: 169 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },

      // Group: Application and Control Plane
      { id: 'upload_service', semanticType: 'service', label: 'Lambda Upload Service', technology: 'Presigned Multipart URLs', icon: 'logos:aws-lambda', position: { x: 1952, y: 540 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'playback_authorization', semanticType: 'service', label: 'Lambda Playback Auth', technology: 'Signed URL / Cookie', icon: 'logos:aws-lambda', position: { x: 1536, y: 230 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'catalog_api', semanticType: 'service', label: 'Lambda Catalog API', technology: 'Video Catalog Query', icon: 'logos:aws-lambda', position: { x: 1536, y: 38 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'video_metadata', semanticType: 'db', label: 'Amazon DynamoDB', technology: 'Metadata & State Store', icon: 'logos:aws-dynamodb', position: { x: 1952, y: 348 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'secrets_manager', semanticType: 'db', label: 'AWS Secrets Manager', technology: 'Encrypted App Config', icon: 'logos:aws-secrets-manager', position: { x: 1536, y: 589 }, size: { w: 224, h: 128 }, detailLevel: 3, properties: {} },

      // Group: Secure Media Ingest
      { id: 'source_bucket', semanticType: 'db', label: 'Amazon S3 Ingest', technology: 'Original Masters', icon: 'logos:aws-s3', position: { x: -768, y: 1171 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'eventbridge', semanticType: 'service', label: 'Amazon EventBridge', technology: 'Object Created Event', icon: 'logos:aws-eventbridge', position: { x: -384, y: 1103 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'processing_workflow', semanticType: 'service', label: 'AWS Step Functions', technology: 'VOD Orchestrator', icon: 'logos:aws-step-functions', position: { x: 64, y: 1176 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'media_validation', semanticType: 'service', label: 'AWS Lambda Validation', technology: 'FFprobe metadata probe', icon: 'logos:aws-lambda', position: { x: 480, y: 1227 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'processing_dlq', semanticType: 'queue', label: 'Amazon SQS DLQ', technology: 'Dead-Letter Queue', icon: 'logos:aws-sqs', position: { x: 864, y: 1179 }, size: { w: 224, h: 128 }, detailLevel: 3, properties: {} },

      // Group: Media Processing Pipeline
      { id: 'media_convert', semanticType: 'service', label: 'AWS Elemental MediaConvert', technology: 'QVBR + ABR Transcoder', icon: 'logos:aws-lambda', position: { x: 2944, y: 1329 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'renditions', semanticType: 'service', label: 'HLS, DASH and MP4 Renditions', technology: 'ABR Playback Profiles', icon: 'lucide:layers-3', position: { x: 3328, y: 1137 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'media_assets', semanticType: 'service', label: 'Thumbnails & Posters', technology: 'Preview clip generators', icon: 'lucide:images', position: { x: 3328, y: 1329 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'distribution_bucket', semanticType: 'db', label: 'Amazon S3 Distribution', technology: 'Versioned assets CDN origin', icon: 'logos:aws-s3', position: { x: 3744, y: 1073 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'kms', semanticType: 'db', label: 'AWS KMS Keys', technology: 'AES-256 Envelope Keys', icon: 'logos:aws-kms', position: { x: 3328, y: 944 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },

      // Group: Global Playback and Product Experience
      { id: 'origin_access_control', semanticType: 'service', label: 'OAC Config', technology: 'CloudFront Origin Access Control', icon: 'logos:aws-cloudfront', position: { x: 1888, y: -284 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'origin_shield', semanticType: 'service', label: 'Origin Shield CDN', technology: 'CloudFront Edge Cache Shield', icon: 'logos:aws-cloudfront', position: { x: 1536, y: -284 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'playback_events', semanticType: 'service', label: 'Playback Events API', technology: 'Event Ingest Endpoint', icon: 'lucide:activity', position: { x: 1536, y: -476 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'data_firehose', semanticType: 'queue', label: 'Amazon Data Firehose', technology: 'Real-time log buffer', icon: 'logos:aws-kinesis', position: { x: 1888, y: -476 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'analytics_lake', semanticType: 'db', label: 'Amazon S3 Analytics', technology: 'Analytics Parquet Lake', icon: 'logos:aws-s3', position: { x: 2240, y: -476 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },

      // Group: Operations, Reliability and Governance
      { id: 'cloudwatch', semanticType: 'service', label: 'Amazon CloudWatch', technology: 'Metrics, Logs & Alarms', icon: 'logos:aws-cloudwatch', position: { x: -2048, y: 1428 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'sns', semanticType: 'service', label: 'Amazon SNS', technology: 'Notifications & Alerts', icon: 'logos:aws-sns', position: { x: -1632, y: 1253 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'xray', semanticType: 'service', label: 'AWS X-Ray', technology: 'Request Tracing', icon: 'logos:aws-xray', position: { x: -2048, y: 786 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'cloudtrail', semanticType: 'service', label: 'AWS CloudTrail', technology: 'Governance Audits', icon: 'logos:aws-cloudtrail', position: { x: -2048, y: 979 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'iam', semanticType: 'service', label: 'AWS IAM Permissions', technology: 'Least Privilege Roles', icon: 'logos:aws-iam', position: { x: -2048, y: 1171 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} }
    ],
    edges: [
      { id: 'e01', sourceNodeId: 'content_admin', targetNodeId: 'cognito', direction: 'forward', label: 'Sign in', detailLevel: 2 },
      { id: 'e02', sourceNodeId: 'content_admin', targetNodeId: 'api_gateway', direction: 'forward', label: 'Request upload session', detailLevel: 1 },
      { id: 'e03', sourceNodeId: 'cognito', targetNodeId: 'api_gateway', direction: 'forward', label: 'JWT tokens', detailLevel: 2 },
      { id: 'e04', sourceNodeId: 'api_gateway', targetNodeId: 'upload_service', direction: 'forward', label: 'Create presigned multipart upload', detailLevel: 2 },
      { id: 'e05', sourceNodeId: 'upload_service', targetNodeId: 'content_admin', direction: 'forward', label: 'Return upload URLs', detailLevel: 2 },
      { id: 'e06', sourceNodeId: 'content_admin', targetNodeId: 'source_bucket', direction: 'forward', label: 'Upload large source file directly', detailLevel: 1 },
      { id: 'e07', sourceNodeId: 'source_bucket', targetNodeId: 'eventbridge', direction: 'forward', label: 'Object-created event', detailLevel: 2 },
      { id: 'e08', sourceNodeId: 'eventbridge', targetNodeId: 'processing_workflow', direction: 'forward', label: 'Start processing execution', detailLevel: 2 },
      { id: 'e09', sourceNodeId: 'eventbridge', targetNodeId: 'processing_workflow', direction: 'forward', label: 'Resume workflow', detailLevel: 2 },
      { id: 'e10', sourceNodeId: 'processing_workflow', targetNodeId: 'media_validation', direction: 'forward', label: 'Validate file and metadata', detailLevel: 2 },
      { id: 'e11', sourceNodeId: 'media_validation', targetNodeId: 'processing_dlq', direction: 'forward', label: 'Invalid media', detailLevel: 3 },
      { id: 'e12', sourceNodeId: 'media_validation', targetNodeId: 'media_convert', direction: 'forward', label: 'Valid media', detailLevel: 2 },
      { id: 'e13', sourceNodeId: 'processing_workflow', targetNodeId: 'media_convert', direction: 'forward', label: 'Submit and monitor job', detailLevel: 2 },
      { id: 'e14', sourceNodeId: 'media_convert', targetNodeId: 'eventbridge', direction: 'forward', label: 'Job status', detailLevel: 2 },
      { id: 'e15', sourceNodeId: 'processing_workflow', targetNodeId: 'video_metadata', direction: 'forward', label: 'Update processing state', detailLevel: 2 },
      { id: 'e16', sourceNodeId: 'processing_workflow', targetNodeId: 'sns', direction: 'forward', label: 'Publish completion or failure', detailLevel: 2 },
      { id: 'e17', sourceNodeId: 'viewers', targetNodeId: 'route53', direction: 'forward', label: 'Open application', detailLevel: 1 },
      { id: 'e18', sourceNodeId: 'route53', targetNodeId: 'waf_shield', direction: 'forward', label: 'Resolve domains', detailLevel: 2 },
      { id: 'e19', sourceNodeId: 'waf_shield', targetNodeId: 'cloudfront', direction: 'forward', label: 'Protected request', detailLevel: 2 },
      { id: 'e20', sourceNodeId: 'viewers', targetNodeId: 'cognito', direction: 'forward', label: 'Authenticate', detailLevel: 2 },
      { id: 'e21', sourceNodeId: 'video_player', targetNodeId: 'api_gateway', direction: 'forward', label: 'Request playback entitlement', detailLevel: 1 },
      { id: 'e22', sourceNodeId: 'api_gateway', targetNodeId: 'playback_authorization', direction: 'forward', label: 'Authorize title', detailLevel: 2 },
      { id: 'e23', sourceNodeId: 'playback_authorization', targetNodeId: 'video_metadata', direction: 'forward', label: 'Read entitlement', detailLevel: 2 },
      { id: 'e24', sourceNodeId: 'playback_authorization', targetNodeId: 'video_player', direction: 'forward', label: 'Return signed access', detailLevel: 2 },
      { id: 'e25', sourceNodeId: 'video_player', targetNodeId: 'cloudfront', direction: 'forward', label: 'Request manifest and segments', detailLevel: 1 },
      { id: 'e26', sourceNodeId: 'cloudfront', targetNodeId: 'origin_shield', direction: 'forward', label: 'Cache miss', detailLevel: 2 },
      { id: 'e27', sourceNodeId: 'origin_shield', targetNodeId: 'origin_access_control', direction: 'forward', label: 'Private origin request', detailLevel: 2 },
      { id: 'e28', sourceNodeId: 'origin_access_control', targetNodeId: 'distribution_bucket', direction: 'forward', label: 'Fetch assets', detailLevel: 2 },
      { id: 'e29', sourceNodeId: 'cloudfront', targetNodeId: 'video_player', direction: 'forward', label: 'Adaptive bitrate stream', detailLevel: 1 },
      { id: 'e30', sourceNodeId: 'api_gateway', targetNodeId: 'catalog_api', direction: 'forward', label: 'Browse and search catalog', detailLevel: 2 },
      { id: 'e31', sourceNodeId: 'catalog_api', targetNodeId: 'video_metadata', direction: 'forward', label: 'Read video catalog', detailLevel: 2 },
      { id: 'e32', sourceNodeId: 'video_player', targetNodeId: 'playback_events', direction: 'forward', label: 'QoE events', detailLevel: 2 },
      { id: 'e33', sourceNodeId: 'playback_events', targetNodeId: 'data_firehose', direction: 'forward', label: 'Stream events', detailLevel: 2 },
      { id: 'e34', sourceNodeId: 'data_firehose', targetNodeId: 'analytics_lake', direction: 'forward', label: 'Store analytics', detailLevel: 2 },
      { id: 'e35', sourceNodeId: 'kms', targetNodeId: 'source_bucket', direction: 'forward', label: 'Encrypt source', detailLevel: 2 },
      { id: 'e36', sourceNodeId: 'kms', targetNodeId: 'distribution_bucket', direction: 'forward', label: 'Encrypt output', detailLevel: 2 },
      { id: 'e37', sourceNodeId: 'secrets_manager', targetNodeId: 'upload_service', direction: 'forward', label: 'App secrets', detailLevel: 3 },
      { id: 'e38', sourceNodeId: 'iam', targetNodeId: 'source_bucket', direction: 'forward', label: 'Service permissions', detailLevel: 2 },
      { id: 'e39', sourceNodeId: 'iam', targetNodeId: 'media_convert', direction: 'forward', label: 'Service permissions', detailLevel: 2 },
      { id: 'e40', sourceNodeId: 'iam', targetNodeId: 'processing_workflow', direction: 'forward', label: 'Service permissions', detailLevel: 2 },
      { id: 'e41', sourceNodeId: 'cloudtrail', targetNodeId: 'api_gateway', direction: 'forward', label: 'Audit control-plane activity', detailLevel: 2 },
      { id: 'e42', sourceNodeId: 'cloudtrail', targetNodeId: 'source_bucket', direction: 'forward', label: 'Audit bucket activity', detailLevel: 2 },
      { id: 'e43', sourceNodeId: 'cloudwatch', targetNodeId: 'processing_workflow', direction: 'forward', label: 'Workflow telemetry', detailLevel: 2 },
      { id: 'e44', sourceNodeId: 'cloudwatch', targetNodeId: 'media_convert', direction: 'forward', label: 'Transcoding metrics and logs', detailLevel: 2 },
      { id: 'e45', sourceNodeId: 'cloudwatch', targetNodeId: 'api_gateway', direction: 'forward', label: 'API alarms', detailLevel: 2 },
      { id: 'e46', sourceNodeId: 'xray', targetNodeId: 'api_gateway', direction: 'forward', label: 'Trace APIs', detailLevel: 2 },
      { id: 'e47', sourceNodeId: 'processing_dlq', targetNodeId: 'cloudwatch', direction: 'forward', label: 'Alarm on failure', detailLevel: 2 },
      { id: 'e48', sourceNodeId: 'cloudwatch', targetNodeId: 'sns', direction: 'forward', label: 'Alert ops team', detailLevel: 2 },
      { id: 'e49', sourceNodeId: 'media_convert', targetNodeId: 'renditions', direction: 'forward', label: 'Generate ABR renditions', detailLevel: 2 },
      { id: 'e50', sourceNodeId: 'media_convert', targetNodeId: 'media_assets', direction: 'forward', label: 'Generate supporting assets', detailLevel: 2 },
      { id: 'e51', sourceNodeId: 'renditions', targetNodeId: 'distribution_bucket', direction: 'forward', label: 'Write packaged media', detailLevel: 2 },
      { id: 'e52', sourceNodeId: 'media_assets', targetNodeId: 'distribution_bucket', direction: 'forward', label: 'Write images and captions', detailLevel: 2 }
    ],
    groups: [
      { id: 'users', label: 'Users and Client Applications', x: -1680, y: -386, w: 320, h: 608, accent: 'blue' },
      { id: 'edge_access', label: 'AWS Edge and Access Layer', x: -665, y: -249, w: 1184, h: 622, accent: 'orange' },
      { id: 'control_plane', label: 'Application and Control Plane', x: 1488, y: -10, w: 736, h: 808, accent: 'purple' },
      { id: 'media_ingest', label: 'Secure Media Ingest', x: -912, y: 1055, w: 2048, h: 389, accent: 'blue' },
      { id: 'processing', label: 'Media Processing Pipeline', x: 2800, y: 896, w: 1216, h: 642, accent: 'orange' },
      { id: 'delivery', label: 'Global Playback and Product Experience', x: 1488, y: -524, w: 1024, h: 416, accent: 'green' },
      { id: 'operations', label: 'Operations, Reliability and Governance', x: -2096, y: 738, w: 736, h: 866, accent: 'slate' }
    ],
    scenarios: []
  },
  {
    version: '1.0.0',
    id: 'global-realtime-messaging',
    kind: 'architecture',
    title: 'Global Real-Time Messaging Platform',
    description: 'A global, low-latency messaging infrastructure featuring WebSocket gateways, distributed session registry, scyllaDB durable message store, Anycast routing, and push services.',
    metadata: {
      complexity: 'Production',
      provider: 'agnostic',
      technologies: ['WebSockets', 'Kafka', 'Cassandra', 'Redis', 'OTel'],
      tags: ['real-time-chat', 'websocket', 'kafka', 'cassandra', 'presence', 'multi-region'],
      detailLevels: ['Executive', 'Engineering', 'Production']
    },
    nodes: [
      // Group: Client Applications
      { id: 'sender_device', semanticType: 'external', label: 'Sender Mobile Device', technology: 'End-to-End Encryption Client', icon: 'lucide:smartphone', position: { x: -1702, y: -402 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'recipient_device', semanticType: 'external', label: 'Recipient Mobile Device', technology: 'Online or Offline Recipient', icon: 'lucide:smartphone', position: { x: -1702, y: -210 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'web_client', semanticType: 'external', label: 'Web and Desktop Client', technology: 'Linked Device Session', icon: 'lucide:monitor', position: { x: -1702, y: -18 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },

      // Group: Global Edge and Connection Layer
      { id: 'global_dns', semanticType: 'service', label: 'Anycast DNS', technology: 'Latency-Based Routing', icon: 'lucide:globe', position: { x: -802, y: -402 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'global_load_balancer', semanticType: 'service', label: 'Global Load Balancer', technology: 'Health-Aware Routing', icon: 'lucide:network', position: { x: -450, y: -402 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'websocket_gateway', semanticType: 'service', label: 'WebSocket Gateway Fleet', technology: 'Long-Lived TLS Connections', icon: 'lucide:radio', position: { x: -50, y: -402 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'api_gateway', semanticType: 'service', label: 'HTTPS API Gateway', technology: 'Uploads & Device APIs', icon: 'logos:aws-api-gateway', position: { x: -450, y: -130 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'edge_rate_limiter', semanticType: 'service', label: 'Distributed Rate Limiter', technology: 'Per User & IP Quotas', icon: 'lucide:gauge', position: { x: -50, y: -130 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },

      // Group: Identity, Device Trust and Key Management
      { id: 'auth_service', semanticType: 'service', label: 'Authentication Service', technology: 'Access & Refresh Tokens', icon: 'lucide:shield-check', position: { x: 648, y: -552 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'device_registry', semanticType: 'db', label: 'Device Registry', technology: 'Trusted session states', icon: 'lucide:smartphone', position: { x: 1000, y: -552 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'key_directory', semanticType: 'service', label: 'Public Key Directory', technology: 'Signed Prekeys Directory', icon: 'lucide:key-round', position: { x: 1352, y: -552 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'abuse_detection', semanticType: 'service', label: 'Abuse & Spam Detection', technology: 'Behavior Metadata Signals', icon: 'lucide:shield-alert', position: { x: 824, y: -312 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'token_cache', semanticType: 'db', label: 'Session Cache', technology: 'Redis Authorization Cache', icon: 'logos:redis', position: { x: 1176, y: -312 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },

      // Group: Regional Messaging Control Plane
      { id: 'chat_ingress', semanticType: 'service', label: 'Chat Ingress Service', technology: 'Validate Envelope Membership', icon: 'lucide:messages-square', position: { x: 648, y: 198 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'idempotency_service', semanticType: 'service', label: 'Idempotency Service', technology: 'Client Message Dedup', icon: 'lucide:copy-check', position: { x: 1000, y: 198 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'conversation_service', semanticType: 'service', label: 'Conversation Service', technology: 'Membership Fanout Policy', icon: 'lucide:users', position: { x: 1352, y: 198 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'presence_service', semanticType: 'service', label: 'Presence Service', technology: 'Online Typing & State', icon: 'lucide:activity', position: { x: 1648, y: 198 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'delivery_router', semanticType: 'service', label: 'Message Delivery Router', technology: 'Online Fanout Router', icon: 'lucide:route', position: { x: 824, y: 486 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'receipt_service', semanticType: 'service', label: 'Delivery Receipt Service', technology: 'Sent, Delivered & Read logs', icon: 'lucide:check-check', position: { x: 1176, y: 486 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'history_service', semanticType: 'service', label: 'Message History Service', technology: 'Cursor Reconnect Sync', icon: 'lucide:history', position: { x: 1528, y: 486 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'session_registry', semanticType: 'db', label: 'Active Session Registry', technology: 'User-Gateway session map', icon: 'logos:redis', position: { x: 824, y: 774 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'offline_delivery', semanticType: 'service', label: 'Offline Delivery Coordinator', technology: 'Push triggers dispatcher', icon: 'lucide:inbox', position: { x: 1176, y: 774 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'group_fanout_worker', semanticType: 'service', label: 'Group Fanout Workers', technology: 'Asynchronous group fanout', icon: 'lucide:git-fork', position: { x: 1528, y: 774 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },

      // Group: Ordering, Durable Storage and Event Backbone
      { id: 'message_stream', semanticType: 'queue', label: 'Message Stream', technology: 'Kafka Partitioned Stream', icon: 'logos:kafka-icon', position: { x: 2398, y: 148 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'receipt_stream', semanticType: 'queue', label: 'Receipt & Presence Stream', technology: 'Independent Event Path', icon: 'logos:kafka-icon', position: { x: 2750, y: 148 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'message_store', semanticType: 'db', label: 'Durable Message Store', technology: 'Cassandra Time-Ordered Rows', icon: 'logos:cassandra', position: { x: 3102, y: 148 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'conversation_store', semanticType: 'db', label: 'Conversation Store', technology: 'Roles & Sequence DB', icon: 'lucide:database', position: { x: 3454, y: 148 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'dedup_store', semanticType: 'db', label: 'Message Dedup Store', technology: 'Short-TTL Message IDs', icon: 'lucide:database-zap', position: { x: 2574, y: 436 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'pending_store', semanticType: 'db', label: 'Pending Delivery Store', technology: 'Per-Device Delivery Cursors', icon: 'lucide:database-clock', position: { x: 2926, y: 436 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'search_index', semanticType: 'db', label: 'Encrypted Metadata Search', technology: 'Server-visible Search Index', icon: 'lucide:search', position: { x: 3278, y: 436 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'retention_worker', semanticType: 'service', label: 'Retention & Deletion Workers', technology: 'Holds & TTL enforcement', icon: 'lucide:trash-2', position: { x: 2750, y: 724 }, size: { w: 224, h: 128 }, detailLevel: 3, properties: {} },
      { id: 'change_data_capture', semanticType: 'queue', label: 'CDC Replication Stream', technology: 'Cross-Region CDC Feed', icon: 'lucide:refresh-cw', position: { x: 3150, y: 724 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },

      // Group: Media Delivery and Push Notifications
      { id: 'media_upload_service', semanticType: 'service', label: 'Media Upload Service', technology: 'Signed Multipart Sessions', icon: 'lucide:upload-cloud', position: { x: 4248, y: -402 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'encrypted_object_storage', semanticType: 'db', label: 'Encrypted Object Storage', technology: 'Client-Encrypted Media', icon: 'lucide:hard-drive', position: { x: 4600, y: -402 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'media_processing', semanticType: 'service', label: 'Media Processing Service', technology: 'Format validation & metadata', icon: 'lucide:image', position: { x: 4952, y: -402 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'media_cdn', semanticType: 'service', label: 'Global Media CDN', technology: 'Short-Lived Signed URLs CDN', icon: 'lucide:cloud', position: { x: 4600, y: -130 }, size: { w: 224, h: 128 }, detailLevel: 1, properties: {} },
      { id: 'push_service', semanticType: 'service', label: 'Push Notification Service', technology: 'Minimal Payload Trigger', icon: 'lucide:bell', position: { x: 4248, y: 142 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'mobile_push_providers', semanticType: 'external', label: 'APNs & FCM', technology: 'Platform Push Providers', icon: 'lucide:send', position: { x: 4600, y: 142 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },

      // Group: Cross-Region Continuity and Failover
      { id: 'home_region_directory', semanticType: 'db', label: 'Global Region Directory', technology: 'User Region Affinity affinity', icon: 'lucide:map-pinned', position: { x: 4248, y: 698 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'replication_pipeline', semanticType: 'queue', label: 'Asynchronous Replication Pipeline', technology: 'Durable CDC pipeline', icon: 'lucide:refresh-ccw', position: { x: 4600, y: 698 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'secondary_message_store', semanticType: 'db', label: 'Secondary Region Store', technology: 'Warm DR Replica DB', icon: 'lucide:database-backup', position: { x: 4952, y: 698 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'failover_controller', semanticType: 'service', label: 'Failover Controller', technology: 'Fencing & routing control', icon: 'lucide:life-buoy', position: { x: 5248, y: 698 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'replay_coordinator', semanticType: 'service', label: 'Recovery Coordinator', technology: 'Rebuild cursors & state', icon: 'lucide:rotate-cw', position: { x: 4600, y: 986 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'conflict_guard', semanticType: 'service', label: 'Writer Epoch Guard', technology: 'Single writer protection', icon: 'lucide:lock-keyhole', position: { x: 4952, y: 986 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },

      // Group: Operations, Reliability and Governance
      { id: 'telemetry_collector', semanticType: 'service', label: 'OTel Collectors', technology: 'Metrics, logs & traces exporter', icon: 'logos:opentelemetry-icon', position: { x: -2252, y: 698 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'metrics_store', semanticType: 'service', label: 'SLO Metrics Store', technology: 'Prometheus-compatible store', icon: 'logos:prometheus', position: { x: -1900, y: 698 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'dashboards', semanticType: 'service', label: 'Grafana Dashboards', technology: 'SLO Latency visualization', icon: 'logos:grafana', position: { x: -2252, y: 938 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'alerting', semanticType: 'service', label: 'SLO Alerting Engine', technology: ' Burn rate alert notifications', icon: 'lucide:siren', position: { x: -1900, y: 938 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'audit_archive', semanticType: 'db', label: 'Immutable Audit logs', technology: 'Security and admin logs archive', icon: 'lucide:scroll-text', position: { x: -2252, y: 1178 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} },
      { id: 'capacity_controller', semanticType: 'service', label: 'Autoscale Controller', technology: 'Partition scale controls', icon: 'lucide:chart-no-axes-combined', position: { x: -1900, y: 1178 }, size: { w: 224, h: 128 }, detailLevel: 2, properties: {} }
    ],
    edges: [
      { id: 'e01', sourceNodeId: 'sender_device', targetNodeId: 'global_dns', direction: 'forward', label: 'Resolve messaging endpoint', detailLevel: 2 },
      { id: 'e02', sourceNodeId: 'recipient_device', targetNodeId: 'global_dns', direction: 'forward', label: 'Resolve messaging endpoint', detailLevel: 2 },
      { id: 'e03', sourceNodeId: 'web_client', targetNodeId: 'global_dns', direction: 'forward', label: 'Resolve messaging endpoint', detailLevel: 2 },
      { id: 'e04', sourceNodeId: 'global_dns', targetNodeId: 'global_load_balancer', direction: 'forward', label: 'Route to nearest region', detailLevel: 1 },
      { id: 'e05', sourceNodeId: 'global_load_balancer', targetNodeId: 'websocket_gateway', direction: 'forward', label: 'Establish TLS connection', detailLevel: 1 },
      { id: 'e06', sourceNodeId: 'global_load_balancer', targetNodeId: 'api_gateway', direction: 'forward', label: 'Route HTTPS API traffic', detailLevel: 1 },
      { id: 'e07', sourceNodeId: 'websocket_gateway', targetNodeId: 'auth_service', direction: 'forward', label: 'Validate access token', detailLevel: 2 },
      { id: 'e08', sourceNodeId: 'api_gateway', targetNodeId: 'auth_service', direction: 'forward', label: 'Authorize API request', detailLevel: 2 },
      { id: 'e09', sourceNodeId: 'auth_service', targetNodeId: 'token_cache', direction: 'forward', label: 'Read auth state', detailLevel: 2 },
      { id: 'e10', sourceNodeId: 'auth_service', targetNodeId: 'device_registry', direction: 'forward', label: 'Verify device', detailLevel: 2 },
      { id: 'e11', sourceNodeId: 'websocket_gateway', targetNodeId: 'edge_rate_limiter', direction: 'forward', label: 'Enforce quotas', detailLevel: 2 },
      { id: 'e12', sourceNodeId: 'edge_rate_limiter', targetNodeId: 'chat_ingress', direction: 'forward', label: 'Forward message envelope', detailLevel: 2 },
      { id: 'e13', sourceNodeId: 'websocket_gateway', targetNodeId: 'session_registry', direction: 'forward', label: 'Register user session', detailLevel: 2 },
      { id: 'e14', sourceNodeId: 'websocket_gateway', targetNodeId: 'presence_service', direction: 'forward', label: 'Heartbeat events', detailLevel: 2 },
      { id: 'e15', sourceNodeId: 'sender_device', targetNodeId: 'key_directory', direction: 'forward', label: 'Fetch identity keys', detailLevel: 2 },
      { id: 'e16', sourceNodeId: 'sender_device', targetNodeId: 'websocket_gateway', direction: 'forward', label: 'Send encrypted message', detailLevel: 1 },
      { id: 'e17', sourceNodeId: 'chat_ingress', targetNodeId: 'abuse_detection', direction: 'forward', label: 'Evaluate abuse signals', detailLevel: 2 },
      { id: 'e18', sourceNodeId: 'chat_ingress', targetNodeId: 'idempotency_service', direction: 'forward', label: 'Validate message ID', detailLevel: 2 },
      { id: 'e19', sourceNodeId: 'idempotency_service', targetNodeId: 'dedup_store', direction: 'forward', label: 'Reserve dedup key', detailLevel: 2 },
      { id: 'e20', sourceNodeId: 'chat_ingress', targetNodeId: 'conversation_service', direction: 'forward', label: 'Verify membership fanout', detailLevel: 2 },
      { id: 'e21', sourceNodeId: 'conversation_service', targetNodeId: 'conversation_store', direction: 'forward', label: 'Read roles states', detailLevel: 2 },
      { id: 'e22', sourceNodeId: 'chat_ingress', targetNodeId: 'message_store', direction: 'forward', label: 'Persist message', detailLevel: 1 },
      { id: 'e23', sourceNodeId: 'message_store', targetNodeId: 'chat_ingress', direction: 'forward', label: 'Write ack', detailLevel: 2 },
      { id: 'e24', sourceNodeId: 'chat_ingress', targetNodeId: 'sender_device', direction: 'forward', label: 'Return status', detailLevel: 2 },
      { id: 'e25', sourceNodeId: 'chat_ingress', targetNodeId: 'message_stream', direction: 'forward', label: 'Publish ordered event', detailLevel: 1 },
      { id: 'e26', sourceNodeId: 'message_stream', targetNodeId: 'group_fanout_worker', direction: 'forward', label: 'Expand group recipients', detailLevel: 2 },
      { id: 'e27', sourceNodeId: 'message_stream', targetNodeId: 'delivery_router', direction: 'forward', label: 'Consume message events', detailLevel: 1 },
      { id: 'e28', sourceNodeId: 'group_fanout_worker', targetNodeId: 'delivery_router', direction: 'forward', label: 'Submit recipient delivery tasks', detailLevel: 2 },
      { id: 'e29', sourceNodeId: 'delivery_router', targetNodeId: 'session_registry', direction: 'forward', label: 'Resolve active sessions', detailLevel: 2 },
      { id: 'e30', sourceNodeId: 'delivery_router', targetNodeId: 'websocket_gateway', direction: 'forward', label: 'Route message to gateway', detailLevel: 1 },
      { id: 'e31', sourceNodeId: 'websocket_gateway', targetNodeId: 'recipient_device', direction: 'forward', label: 'Deliver message', detailLevel: 1 },
      { id: 'e32', sourceNodeId: 'delivery_router', targetNodeId: 'offline_delivery', direction: 'forward', label: 'No active session', detailLevel: 2 },
      { id: 'e33', sourceNodeId: 'offline_delivery', targetNodeId: 'pending_store', direction: 'forward', label: 'Record pending delivery', detailLevel: 2 },
      { id: 'e34', sourceNodeId: 'offline_delivery', targetNodeId: 'push_service', direction: 'forward', label: 'Request wake-up push', detailLevel: 2 },
      { id: 'e35', sourceNodeId: 'push_service', targetNodeId: 'mobile_push_providers', direction: 'forward', label: 'Send push request', detailLevel: 2 },
      { id: 'e36', sourceNodeId: 'mobile_push_providers', targetNodeId: 'recipient_device', direction: 'forward', label: 'Wake application', detailLevel: 2 },
      { id: 'e37', sourceNodeId: 'recipient_device', targetNodeId: 'websocket_gateway', direction: 'forward', label: 'Reconnect & send receipt', detailLevel: 2 },
      { id: 'e38', sourceNodeId: 'websocket_gateway', targetNodeId: 'receipt_service', direction: 'forward', label: 'Forward receipts', detailLevel: 2 },
      { id: 'e39', sourceNodeId: 'receipt_service', targetNodeId: 'receipt_stream', direction: 'forward', label: 'Publish receipt event', detailLevel: 2 },
      { id: 'e40', sourceNodeId: 'receipt_service', targetNodeId: 'message_store', direction: 'forward', label: 'Update state', detailLevel: 2 },
      { id: 'e41', sourceNodeId: 'receipt_stream', targetNodeId: 'delivery_router', direction: 'forward', label: 'Route receipt to sender', detailLevel: 2 },
      { id: 'e42', sourceNodeId: 'api_gateway', targetNodeId: 'history_service', direction: 'forward', label: 'Request history sync', detailLevel: 2 },
      { id: 'e43', sourceNodeId: 'history_service', targetNodeId: 'message_store', direction: 'forward', label: 'Read time-ordered messages', detailLevel: 2 },
      { id: 'e44', sourceNodeId: 'history_service', targetNodeId: 'pending_store', direction: 'forward', label: 'Read delivery cursor', detailLevel: 2 },
      { id: 'e45', sourceNodeId: 'history_service', targetNodeId: 'recipient_device', direction: 'forward', label: 'Return missed messages', detailLevel: 2 },
      { id: 'e46', sourceNodeId: 'sender_device', targetNodeId: 'api_gateway', direction: 'forward', label: 'Request signed media upload', detailLevel: 1 },
      { id: 'e47', sourceNodeId: 'api_gateway', targetNodeId: 'media_upload_service', direction: 'forward', label: 'Create upload session', detailLevel: 2 },
      { id: 'e48', sourceNodeId: 'media_upload_service', targetNodeId: 'sender_device', direction: 'forward', label: 'Return upload URLs', detailLevel: 2 },
      { id: 'e49', sourceNodeId: 'sender_device', targetNodeId: 'encrypted_object_storage', direction: 'forward', label: 'Upload encrypted media', detailLevel: 1 },
      { id: 'e50', sourceNodeId: 'encrypted_object_storage', targetNodeId: 'media_processing', direction: 'forward', label: 'Validate format', detailLevel: 2 },
      { id: 'e51', sourceNodeId: 'encrypted_object_storage', targetNodeId: 'media_cdn', direction: 'forward', label: 'Serve media origin', detailLevel: 2 },
      { id: 'e52', sourceNodeId: 'media_cdn', targetNodeId: 'recipient_device', direction: 'forward', label: 'Download encrypted media', detailLevel: 1 },
      { id: 'e53', sourceNodeId: 'websocket_gateway', targetNodeId: 'home_region_directory', direction: 'forward', label: 'Resolve home region', detailLevel: 2 },
      { id: 'e54', sourceNodeId: 'message_store', targetNodeId: 'change_data_capture', direction: 'forward', label: 'Emit message CDC', detailLevel: 2 },
      { id: 'e55', sourceNodeId: 'change_data_capture', targetNodeId: 'replication_pipeline', direction: 'forward', label: 'Replicate CDC feed', detailLevel: 2 },
      { id: 'e56', sourceNodeId: 'replication_pipeline', targetNodeId: 'secondary_message_store', direction: 'forward', label: 'Write DR Replica', detailLevel: 2 },
      { id: 'e57', sourceNodeId: 'failover_controller', targetNodeId: 'global_load_balancer', direction: 'forward', label: 'Shift traffic', detailLevel: 2 },
      { id: 'e58', sourceNodeId: 'failover_controller', targetNodeId: 'conflict_guard', direction: 'forward', label: 'Issue writer epoch', detailLevel: 2 },
      { id: 'e59', sourceNodeId: 'conflict_guard', targetNodeId: 'secondary_message_store', direction: 'forward', label: 'Permit recovery mode writes', detailLevel: 2 },
      { id: 'e60', sourceNodeId: 'secondary_message_store', targetNodeId: 'replay_coordinator', direction: 'forward', label: 'Provide cursors', detailLevel: 2 },
      { id: 'e61', sourceNodeId: 'replay_coordinator', targetNodeId: 'delivery_router', direction: 'forward', label: 'Resume pending delivery', detailLevel: 2 },
      { id: 'e62', sourceNodeId: 'retention_worker', targetNodeId: 'message_store', direction: 'forward', label: 'Apply holds policy', detailLevel: 2 },
      { id: 'e63', sourceNodeId: 'retention_worker', targetNodeId: 'encrypted_object_storage', direction: 'forward', label: 'Delete expired objects', detailLevel: 2 },
      { id: 'e64', sourceNodeId: 'search_index', targetNodeId: 'history_service', direction: 'forward', label: 'Resolve search filters', detailLevel: 2 },
      { id: 'e65', sourceNodeId: 'websocket_gateway', targetNodeId: 'telemetry_collector', direction: 'forward', label: 'Connection telemetry', detailLevel: 2 },
      { id: 'e66', sourceNodeId: 'chat_ingress', targetNodeId: 'telemetry_collector', direction: 'forward', label: 'Ingress trace metrics', detailLevel: 2 },
      { id: 'e67', sourceNodeId: 'delivery_router', targetNodeId: 'telemetry_collector', direction: 'forward', label: 'Router delay telemetry', detailLevel: 2 },
      { id: 'e68', sourceNodeId: 'message_stream', targetNodeId: 'telemetry_collector', direction: 'forward', label: 'Partition lag metrics', detailLevel: 2 },
      { id: 'e69', sourceNodeId: 'telemetry_collector', targetNodeId: 'metrics_store', direction: 'forward', label: 'Export SLO metrics', detailLevel: 2 },
      { id: 'e70', sourceNodeId: 'metrics_store', targetNodeId: 'dashboards', direction: 'forward', label: 'SLO dashboards', detailLevel: 2 },
      { id: 'e71', sourceNodeId: 'metrics_store', targetNodeId: 'alerting', direction: 'forward', label: 'Evaluate SLO alerts', detailLevel: 2 },
      { id: 'e72', sourceNodeId: 'auth_service', targetNodeId: 'audit_archive', direction: 'forward', label: 'Audit identities state', detailLevel: 2 },
      { id: 'e73', sourceNodeId: 'key_directory', targetNodeId: 'audit_archive', direction: 'forward', label: 'Audit keys rotation state', detailLevel: 2 },
      { id: 'e74', sourceNodeId: 'capacity_controller', targetNodeId: 'websocket_gateway', direction: 'forward', label: 'Scale gateway capacity', detailLevel: 2 },
      { id: 'e75', sourceNodeId: 'capacity_controller', targetNodeId: 'message_stream', direction: 'forward', label: 'Rebalance stream partitions' }
    ],
    groups: [
      { id: 'clients', label: 'Client Applications', x: -1750, y: -450, w: 320, h: 704, accent: 'sky' },
      { id: 'edge_connection', label: 'Global Edge and Connection Layer', x: -850, y: -450, w: 1184, h: 750, accent: 'amber' },
      { id: 'identity_security', label: 'Identity, Device Trust and Key Management', x: 600, y: -600, w: 1050, h: 550, accent: 'violet' },
      { id: 'messaging_core', label: 'Regional Messaging Control Plane', x: 600, y: 150, w: 1400, h: 1000, accent: 'sky' },
      { id: 'ordering_storage', label: 'Ordering, Durable Storage and Event Backbone', x: 2350, y: 100, w: 1550, h: 1000, accent: 'orange' },
      { id: 'media_notifications', label: 'Media Delivery and Push Notifications', x: 4200, y: -450, w: 1150, h: 900, accent: 'green' },
      { id: 'cross_region', label: 'Cross-Region Continuity and Failover', x: 4200, y: 650, w: 1350, h: 800, accent: 'green' },
      { id: 'operations', label: 'Operations, Reliability and Governance', x: -2300, y: 650, w: 800, h: 1000, accent: 'slate' }
    ],
    scenarios: []
  }
];
